import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Flutter Cameroon</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/images/11.svg" />
      </Head>

      <main className={styles.main}>

        
      </main>
    </div>
  )
}
